- hosts: all
  gather_facts: False
  become: True
  tasks:
  - name: install python 2
    raw: sudo bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qy python-minimal)"

- name: install emulator
  hosts: all
  become: True
  tasks:
  - name: check if KVM is available
    shell: egrep -c '(vmx|svm)' /proc/cpuinfo 
    register: kvm
    failed_when: kvm.stdout == 0
  - name: install KVM and pip
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - qemu-kvm 
      - libvirt-daemon-system 
      - libvirt-clients 
      - bridge-utils
      - python-pip
  - name: Import Docker CE repository gpg key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
  - name: Import Docker repository key from ubuntu keyserver
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: 7EA0A9C3F273FCD8
  - name: Add Docker CE repository
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      state: present
  - name: Install docker
    apt:
      name: docker-ce
      state: present
      update_cache: yes
    register: docker_install
  - set_fact: changed="{{ changed is defined and (changed or docker_install.changed) }}"  
  # https://github.com/agoda-com/docker-emulator-android
  - name: install docker-py
    pip:
      name: docker-py
  - name: Run android emulator container
    docker_container:
      name: android-emulator-23
      image: mwall2bitflow/android-emulator-23 
      env:
          ANDROID_ARCH: "x86"
      pull: true
      ports:
        - "5555:5555"
        - "5900:5900"
      devices:
       - "/dev/kvm:/dev/kvm"
      network_mode: host
      pid_mode: host
      privileged: yes
      command: ""
